name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/local-s3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Build and Package
      run: mvn package -Dmaven.test.skip=true
    - name: Run tests
      timeout-minutes: 10
      run: mvn test
